/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     8/24/2020 2:02:30 PM                         */
/*==============================================================*/


DROP USER DBA_BV01 CASCADE;
DROP USER XX CASCADE;

CREATE USER DBA_BV01 IDENTIFIED BY "1";
CREATE USER XX IDENTIFIED BY "1231";

GRANT ALL PRIVILEGES TO DBA_BV01, XX;
GRANT DBA TO DBA_BV01;

ALTER USER XX ACCOUNT LOCK;

CONN DBA_BV01/1;

ALTER TABLE "CHITIETDICHVUHD"
   DROP CONSTRAINT FK_CHITIETD_REFERENCE_THONGTIN;

ALTER TABLE "CHITIETDICHVUHD"
   DROP CONSTRAINT FK_CHITIETD_REFERENCE_DICHVU;

ALTER TABLE "CHITIETDICHVUHD"
   DROP CONSTRAINT FK_CHITIETD_REFERENCE_NHANVIEN;

ALTER TABLE "CHITIETTHUOCHD"
   DROP CONSTRAINT FK_CHITIETT_REFERENCE_THONGTIN;

ALTER TABLE "CHITIETTHUOCHD"
   DROP CONSTRAINT FK_CHITIETT_REFERENCE_THUOC;

ALTER TABLE "CUOCHOP"
   DROP CONSTRAINT FK_CUOCHOP_REFERENCE_NHANVIEN;

ALTER TABLE LUONG
   DROP CONSTRAINT FK_LUONG_REFERENCE_NHANVIEN;

ALTER TABLE "LICHTRUC"
   DROP CONSTRAINT FK_LICHTRUC_REFERENCE_PHONG;

ALTER TABLE "LICHTRUC"
   DROP CONSTRAINT FK_LICHTRUC_REFERENCE_NHANVIEN;

ALTER TABLE THONGTINKHAMBENH
   DROP CONSTRAINT FK_THONGTIN_REFERENCE_BENHNHAN;

ALTER TABLE THONGTINKHAMBENH
   DROP CONSTRAINT FK_THONGTIN_REFERENCE_NHANVIEN;

DROP TABLE BENHNHAN CASCADE CONSTRAINTS;

DROP TABLE "CHITIETDICHVUHD" CASCADE CONSTRAINTS;

DROP TABLE "CHITIETTHUOCHD" CASCADE CONSTRAINTS;

DROP TABLE "CUOCHOP" CASCADE CONSTRAINTS;

DROP TABLE DICHVU CASCADE CONSTRAINTS;

DROP TABLE LUONG CASCADE CONSTRAINTS;

DROP TABLE "LICHTRUC" CASCADE CONSTRAINTS;

DROP TABLE NHANVIEN CASCADE CONSTRAINTS;

DROP TABLE PHONG CASCADE CONSTRAINTS;

DROP TABLE THONGTINKHAMBENH CASCADE CONSTRAINTS;

DROP TABLE THUOC CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: BENHNHAN                                              */
/*==============================================================*/
CREATE TABLE BENHNHAN 
(
   "MABENHNHAN"         INTEGER              NOT NULL,
   "TEN"                VARCHAR2(50),
   "NAMSINH"            INTEGER,
   "DIACHI"             VARCHAR2(50),
   "SODIENTHOAI"        VARCHAR2(20),
   CONSTRAINT PK_BENHNHAN PRIMARY KEY ("MABENHNHAN")
);

COMMENT ON TABLE BENHNHAN IS
'BENHNHAN';

COMMENT ON COLUMN BENHNHAN."MABENHNHAN" IS
'Mabenhnhan';

COMMENT ON COLUMN BENHNHAN."TEN" IS
'Ten';

COMMENT ON COLUMN BENHNHAN."NAMSINH" IS
'Namsinh';

COMMENT ON COLUMN BENHNHAN."DIACHI" IS
'Diachi';

COMMENT ON COLUMN BENHNHAN."SODIENTHOAI" IS
'Sodienthoai';

/*==============================================================*/
/* Table: "CHITIETDICHVUHD"                                     */
/*==============================================================*/
CREATE TABLE "CHITIETDICHVUHD" 
(
   "MACHITIETDICHVU"    INTEGER              NOT NULL,
   "MATHONGTINKHAMBENH" INTEGER,
   "MADICHVU"           INTEGER,
   "MANV"               INTEGER,
   "TENDV"              VARCHAR2(50),
   "SOLAN"              INTEGER,
   "THANHTIEN"          FLOAT,
   "PHONG"              VARCHAR2(50),
   CONSTRAINT PK_CHITIETDICHVUHD PRIMARY KEY ("MACHITIETDICHVU")
);

COMMENT ON TABLE "CHITIETDICHVUHD" IS
'CHITIETDICHVU_HD';

COMMENT ON COLUMN "CHITIETDICHVUHD"."MACHITIETDICHVU" IS
'Machitietdichvu';

COMMENT ON COLUMN "CHITIETDICHVUHD"."MATHONGTINKHAMBENH" IS
'Mathongtinkhambenh';

COMMENT ON COLUMN "CHITIETDICHVUHD"."MADICHVU" IS
'Madichvu';

COMMENT ON COLUMN "CHITIETDICHVUHD"."MANV" IS
'Manv';

COMMENT ON COLUMN "CHITIETDICHVUHD"."TENDV" IS
'Tendv';

COMMENT ON COLUMN "CHITIETDICHVUHD"."SOLAN" IS
'Solan';

COMMENT ON COLUMN "CHITIETDICHVUHD"."THANHTIEN" IS
'Thanhtien';

COMMENT ON COLUMN "CHITIETDICHVUHD"."PHONG" IS
'Phong';

/*==============================================================*/
/* Table: "CHITIETTHUOCHD"                                      */
/*==============================================================*/
CREATE TABLE "CHITIETTHUOCHD" 
(
   "MACHITIETTHUOC"     INTEGER              NOT NULL,
   "MATHONGTINKHAMBENH" INTEGER,
   "MATHUOC"            INTEGER,
   "SOLUONG"            INTEGER,
   "CACHDUNG"           VARCHAR2(50),
   "THANHTIEN"          FLOAT,
   CONSTRAINT PK_CHITIETTHUOCHD PRIMARY KEY ("MACHITIETTHUOC")
);

COMMENT ON TABLE "CHITIETTHUOCHD" IS
'CHITIETTHUOC_HD';

COMMENT ON COLUMN "CHITIETTHUOCHD"."MACHITIETTHUOC" IS
'Machitietthuoc';

COMMENT ON COLUMN "CHITIETTHUOCHD"."MATHONGTINKHAMBENH" IS
'Mathongtinkhambenh';

COMMENT ON COLUMN "CHITIETTHUOCHD"."MATHUOC" IS
'Mathuoc';

COMMENT ON COLUMN "CHITIETTHUOCHD"."SOLUONG" IS
'Soluong';

COMMENT ON COLUMN "CHITIETTHUOCHD"."CACHDUNG" IS
'Cachdung';

COMMENT ON COLUMN "CHITIETTHUOCHD"."THANHTIEN" IS
'Thanhtien';

/*==============================================================*/
/* Table: "CUOCHOP"                                             */
/*==============================================================*/
CREATE TABLE "CUOCHOP" 
(
   "MACUOCHOP"          INTEGER              NOT NULL,
   "NVCHUTRI"           INTEGER,
   "NOIDUNG"            NVARCHAR2(50),
   CONSTRAINT PK_CUOCHOP PRIMARY KEY ("MACUOCHOP")
);

COMMENT ON TABLE "CUOCHOP" IS
'CUOC HOP';

COMMENT ON COLUMN "CUOCHOP"."MACUOCHOP" IS
'Ma Cuoc Hop';

COMMENT ON COLUMN "CUOCHOP"."NVCHUTRI" IS
'Nv Chu Tri';

COMMENT ON COLUMN "CUOCHOP"."NOIDUNG" IS
'Noi Dung';

/*==============================================================*/
/* Table: DICHVU                                                */
/*==============================================================*/
CREATE TABLE DICHVU 
(
   "MADICHVU"           INTEGER              NOT NULL,
   "TENDV"              VARCHAR2(50),
   "DONGIA"             FLOAT,
   CONSTRAINT PK_DICHVU PRIMARY KEY ("MADICHVU")
);

COMMENT ON TABLE DICHVU IS
'DICHVU';

COMMENT ON COLUMN DICHVU."MADICHVU" IS
'Madichvu';

COMMENT ON COLUMN DICHVU."TENDV" IS
'Tendv';

COMMENT ON COLUMN DICHVU."DONGIA" IS
'Dongia';

/*==============================================================*/
/* Table: LUONG                                                 */
/*==============================================================*/
CREATE TABLE LUONG 
(
   "MALUONG"            INTEGER              NOT NULL,
   "MANV"               INTEGER              NOT NULL,
   "THANG"              INTEGER              NOT NULL,
   "NAM"                INTEGER              NOT NULL,
   "NGAYCONG"           INTEGER,
   "PHUCAP"             FLOAT,
   "TONGLUONG"          FLOAT,
   CONSTRAINT PK_LUONG PRIMARY KEY ("MALUONG")
);

COMMENT ON TABLE LUONG IS
'LUONG';

COMMENT ON COLUMN LUONG."MALUONG" IS
'Maluong';

COMMENT ON COLUMN LUONG."MANV" IS
'Manv';

COMMENT ON COLUMN LUONG."THANG" IS
'Thang';

COMMENT ON COLUMN LUONG."NAM" IS
'Nam';

COMMENT ON COLUMN LUONG."NGAYCONG" IS
'Ngaycong';

COMMENT ON COLUMN LUONG."PHUCAP" IS
'Phucap';

COMMENT ON COLUMN LUONG."TONGLUONG" IS
'Tongluong';

/*==============================================================*/
/* Table: "LICHTRUC"                                            */
/*==============================================================*/
CREATE TABLE "LICHTRUC" 
(
   MALICHTRUC           INTEGER              NOT NULL,
   "MAPHONG"            INTEGER,
   "MANV"               INTEGER,
   NGAY                 DATE,
   CONSTRAINT PK_LICHTRUC PRIMARY KEY (MALICHTRUC)
);

COMMENT ON TABLE "LICHTRUC" IS
'LICH TRUC';

COMMENT ON COLUMN "LICHTRUC".MALICHTRUC IS
'Malichtruc';

COMMENT ON COLUMN "LICHTRUC"."MAPHONG" IS
'Ma Phong';

COMMENT ON COLUMN "LICHTRUC"."MANV" IS
'Manv';

COMMENT ON COLUMN "LICHTRUC".NGAY IS
'Ngay';

/*==============================================================*/
/* Table: NHANVIEN                                              */
/*==============================================================*/
CREATE TABLE NHANVIEN 
(
   "MANV"               INTEGER              NOT NULL,
   "TENNV"              VARCHAR2(50)
   "LOAINV"             VARCHAR2(50),
   "LUONGCB"            FLOAT,
   CONSTRAINT PK_NHANVIEN PRIMARY KEY ("MANV")
);

COMMENT ON TABLE NHANVIEN IS
'NHANVIEN';

COMMENT ON COLUMN NHANVIEN."MANV" IS
'Manv';

COMMENT ON COLUMN NHANVIEN."TENNV" IS
'Tennv';

COMMENT ON COLUMN NHANVIEN."LOAINV" IS
'Loainv';

COMMENT ON COLUMN NHANVIEN."LUONGCB" IS
'Luongcb';

/*==============================================================*/
/* Table: PHONG                                                 */
/*==============================================================*/
CREATE TABLE PHONG 
(
   "MAPHONG"            INTEGER              NOT NULL,
   "TINHTRANG"          VARCHAR2(50),
   CONSTRAINT PK_PHONG PRIMARY KEY ("MAPHONG")
);

COMMENT ON TABLE PHONG IS
'PHONG';

COMMENT ON COLUMN PHONG."MAPHONG" IS
'Ma Phong';

COMMENT ON COLUMN PHONG."TINHTRANG" IS
'Tinh Trang';

/*==============================================================*/
/* Table: THONGTINKHAMBENH                                      */
/*==============================================================*/
CREATE TABLE THONGTINKHAMBENH 
(
   "MATHONGTINKHAMBENH" INTEGER              NOT NULL,
   "MABENHNHAN"         INTEGER,
   "BACSI"              INTEGER,
   "NGAYKHAM"           DATE,
   "TRIEUCHUNG"         VARCHAR2(50),
   "LOIDAN"             VARCHAR2(50),
   "PHONG"              VARCHAR2(50),
   CONSTRAINT PK_THONGTINKHAMBENH PRIMARY KEY ("MATHONGTINKHAMBENH")
);

COMMENT ON TABLE THONGTINKHAMBENH IS
'THONGTINKHAMBENH';

COMMENT ON COLUMN THONGTINKHAMBENH."MATHONGTINKHAMBENH" IS
'Mathongtinkhambenh';

COMMENT ON COLUMN THONGTINKHAMBENH."MABENHNHAN" IS
'Mabenhnhan';

COMMENT ON COLUMN THONGTINKHAMBENH."BACSI" IS
'Bacsi';

COMMENT ON COLUMN THONGTINKHAMBENH."NGAYKHAM" IS
'Ngaykham';

COMMENT ON COLUMN THONGTINKHAMBENH."TRIEUCHUNG" IS
'Trieuchung';

COMMENT ON COLUMN THONGTINKHAMBENH."LOIDAN" IS
'Loidan';

COMMENT ON COLUMN THONGTINKHAMBENH."PHONG" IS
'Phong';

/*==============================================================*/
/* Table: THUOC                                                 */
/*==============================================================*/
CREATE TABLE THUOC 
(
   "MATHUOC"            INTEGER              NOT NULL,
   "TENTHUOC"           VARCHAR2(50),
   "DONGIA"             FLOAT,
   "TONKHO"             INTEGER,
   CONSTRAINT PK_THUOC PRIMARY KEY ("MATHUOC")
);

COMMENT ON TABLE THUOC IS
'THUOC';

COMMENT ON COLUMN THUOC."MATHUOC" IS
'Mathuoc';

COMMENT ON COLUMN THUOC."TENTHUOC" IS
'Tenthuoc';

COMMENT ON COLUMN THUOC."DONGIA" IS
'Dongia';

COMMENT ON COLUMN THUOC."TONKHO" IS
'Tonkho';

ALTER TABLE "CHITIETDICHVUHD"
   ADD CONSTRAINT FK_CHITIETD_REFERENCE_THONGTIN FOREIGN KEY ("MATHONGTINKHAMBENH")
      REFERENCES THONGTINKHAMBENH ("MATHONGTINKHAMBENH");

ALTER TABLE "CHITIETDICHVUHD"
   ADD CONSTRAINT FK_CHITIETD_REFERENCE_DICHVU FOREIGN KEY ("MADICHVU")
      REFERENCES DICHVU ("MADICHVU");

ALTER TABLE "CHITIETDICHVUHD"
   ADD CONSTRAINT FK_CHITIETD_REFERENCE_NHANVIEN FOREIGN KEY ("MANV")
      REFERENCES NHANVIEN ("MANV");

ALTER TABLE "CHITIETTHUOCHD"
   ADD CONSTRAINT FK_CHITIETT_REFERENCE_THONGTIN FOREIGN KEY ("MATHONGTINKHAMBENH")
      REFERENCES THONGTINKHAMBENH ("MATHONGTINKHAMBENH");

ALTER TABLE "CHITIETTHUOCHD"
   ADD CONSTRAINT FK_CHITIETT_REFERENCE_THUOC FOREIGN KEY ("MATHUOC")
      REFERENCES THUOC ("MATHUOC");

ALTER TABLE "CUOCHOP"
   ADD CONSTRAINT FK_CUOCHOP_REFERENCE_NHANVIEN FOREIGN KEY ("NVCHUTRI")
      REFERENCES NHANVIEN ("MANV");

ALTER TABLE LUONG
   ADD CONSTRAINT FK_LUONG_REFERENCE_NHANVIEN FOREIGN KEY ("MANV")
      REFERENCES NHANVIEN ("MANV");

ALTER TABLE "LICHTRUC"
   ADD CONSTRAINT FK_LICHTRUC_REFERENCE_PHONG FOREIGN KEY ("MAPHONG")
      REFERENCES PHONG ("MAPHONG");

ALTER TABLE "LICHTRUC"
   ADD CONSTRAINT FK_LICHTRUC_REFERENCE_NHANVIEN FOREIGN KEY ("MANV")
      REFERENCES NHANVIEN ("MANV");

ALTER TABLE THONGTINKHAMBENH
   ADD CONSTRAINT FK_THONGTIN_REFERENCE_BENHNHAN FOREIGN KEY ("MABENHNHAN")
      REFERENCES BENHNHAN ("MABENHNHAN");

ALTER TABLE THONGTINKHAMBENH
   ADD CONSTRAINT FK_THONGTIN_REFERENCE_NHANVIEN FOREIGN KEY ("BACSI")
      REFERENCES NHANVIEN ("MANV");